// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFLLbUUKKQSP-l_m3YReOarFZEBjEDJPE',
    appId: '1:560853982629:web:d12f94475e69d627d69c4c',
    messagingSenderId: '560853982629',
    projectId: 'fireproject-90fa8',
    authDomain: 'fireproject-90fa8.firebaseapp.com',
    storageBucket: 'fireproject-90fa8.firebasestorage.app',
    measurementId: 'G-8EWZKQTPZ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7cxKkvClpEop9h1qOjZrq1PRrGVgPqRU',
    appId: '1:560853982629:android:2b05e8b17fe79cc7d69c4c',
    messagingSenderId: '560853982629',
    projectId: 'fireproject-90fa8',
    storageBucket: 'fireproject-90fa8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVuO6K6mMgEH8i3aDF99GyZ_6kWVsKXBU',
    appId: '1:560853982629:ios:afb7a91555f5e940d69c4c',
    messagingSenderId: '560853982629',
    projectId: 'fireproject-90fa8',
    storageBucket: 'fireproject-90fa8.firebasestorage.app',
    iosBundleId: 'com.example.bmiNewApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVuO6K6mMgEH8i3aDF99GyZ_6kWVsKXBU',
    appId: '1:560853982629:ios:afb7a91555f5e940d69c4c',
    messagingSenderId: '560853982629',
    projectId: 'fireproject-90fa8',
    storageBucket: 'fireproject-90fa8.firebasestorage.app',
    iosBundleId: 'com.example.bmiNewApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFLLbUUKKQSP-l_m3YReOarFZEBjEDJPE',
    appId: '1:560853982629:web:104a3bf122a02d87d69c4c',
    messagingSenderId: '560853982629',
    projectId: 'fireproject-90fa8',
    authDomain: 'fireproject-90fa8.firebaseapp.com',
    storageBucket: 'fireproject-90fa8.firebasestorage.app',
    measurementId: 'G-XCC6PRTQMM',
  );

}